# fly.toml app configuration file generated for sendnotes-aged-paper-1547 on 2024-10-11T15:34:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sendnotes-aged-paper-1547'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = "pgsql"
  DATABASE_URL = "postgres://sendnotes_aged_paper_1547:MR3YedB21j7glDs@sendnotes-db.flycast:5432/sendnotes_aged_paper_1547?sslmode=disable"
  APP_URL = "https://sendnotes-aged-paper-1547.fly.dev"
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
release_command = "php /var/www/html/artisan migrate --force"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
